spring.application.name=Arashyn-BE

# PostgreSQL (Supabase)
spring.datasource.url=${DB_ARASHYN_URL}
spring.datasource.username=${DB_ARASHYN_USERNAME}
spring.datasource.password=${DB_ARASHYN_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Swagger
springdoc.swagger-ui.path=/swagger

# Supabase Auth
supabase.url=${SUPABASE_URL}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}